export function buildTemplateExecutionSnapshot(goal = ""): string[] {
	return [
		`## Execution Snapshot`,
		``,
		`### Objective`,
		goal ? `> ${goal}` : `> What we are trying to accomplish.`,
		``,
		`### Completed`,
		`- `,
		``,
		`### In Progress`,
		`- `,
		``,
		`### Important Discoveries`,
		`- `,
		``,
		`### Decisions`,
		`- `,
		``,
		`### Constraints`,
		`- `,
		``,
		`### Files Examined`,
		`- `,
		``,
		`### Files Modified`,
		`- `,
		``,
		`### Test / Build Status`,
		`- `,
		``,
		`### Known Problems / Uncertainties`,
		`- `,
		``,
		`### Remaining Work`,
		`- [ ] `,
		``,
		`### Exact Next Action`,
		`> `,
		``,
		`### Resume Context`,
		`> `,
		``,
	];
}

export function buildTemplateFooterSections(refinements: string[] = []): string[] {
	const refinementsBody = refinements && refinements.length > 0
		? refinements.map((r) => `- ${r}`).join("\n")
		: `- `;
	return [
		`## Decisions Made`,
		`- `,
		``,
		`## Constraints & Rules`,
		`- `,
		``,
		`## Files Touched`,
		`- `,
		``,
		`## Test / Build Status`,
		`- `,
		``,
		`## Sub-Quests`,
		`> Planned sub-quests, follow-ups, or tangent quests linked to this quest.`,
		`- [ ] `,
		``,
		`## Quest Refinements & User Feedback Loops`,
		`> Mid-workflow refinements, post-implementation iterations, and user adjustments.`,
		refinementsBody,
		``,
		`## Remaining Work`,
		`- [ ] `,
		``,
		`## Exact Next Action`,
		`> Most justified immediate action (investigate, verify assumption, revise plan, implement, run tests).`,
		``,
		`## Resume Context`,
		`> Concise epistemic briefing for continuing this quest without repeating solved research.`,
		``,
	];
}
