include $(HOME)/mk/portable.mk

REPO_ROOT != cd ../.. && pwd
MOD_NAME != basename "$$(pwd)"
TARGET_AUTO != case "$$(pwd)" in */modules/*) printf 'be/nd_%s.%s\n' "$$(basename "$$(pwd)")" "${SO}";; *) printf '%s.%s\n' "$$(basename "$$(pwd)")" "${SO}";; esac
SRC_AUTO != case "$$(pwd)" in */modules/*) printf 'be/nd_%s.c\n' "$$(basename "$$(pwd)")";; *) printf '%s.c\n' "$$(basename "$$(pwd)")";; esac
PICFLAGS-Unix = -fPIC
PICFLAGS = ${PICFLAGS-${SYS}}

TARGET ?= $(TARGET_AUTO)
SRC ?= $(SRC_AUTO)
MAKEFILE_DEPS = Makefile $(REPO_ROOT)/build.mk

CC ?= clang

SANITIZE ?= 0
ifeq ($(SANITIZE),1)
CFLAGS += -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer
LDFLAGS += -fsanitize=address -fsanitize=undefined
endif
PROFILE ?= dev
ifeq ($(PROFILE),release)
CFLAGS += -O2 -DNDEBUG $(PICFLAGS)
else
CFLAGS += -g -O0 $(PICFLAGS)
endif
CFLAGS += -I$(REPO_ROOT)/external/axil/include -I$(REPO_ROOT)/external/qmap/include -I$(REPO_ROOT)/external/libxylem/include -I$(REPO_ROOT)/external/bud/include -I$(REPO_ROOT)/external/hyle/include -I$(REPO_ROOT)/external/hyle/c/libhyle-source/include
CFLAGS += $(EXTRA_CFLAGS)

LDFLAGS += -shared
LDFLAGS += -L$(REPO_ROOT)/external/axil/lib -L$(REPO_ROOT)/external/qmap/lib
LDFLAGS += -L$(REPO_ROOT)/external/axil-auth/lib

LDLIBS += -laxil -lqmap
LDLIBS += $(EXTRA_LDLIBS)
LDLIBS += $(EXTRA_LDLIBS-$(uname))

WASM_PATH ?= $(REPO_ROOT)/htdocs
WASI_CC      ?= clang
WASI_SYSROOT ?=
ifeq ($(PROFILE),release)
WASM_CFLAGS  ?= -O2 -DNDEBUG -D__wasm__ --target=wasm32-wasi
else
WASM_CFLAGS  ?= -g -O0 -D__wasm__ --target=wasm32-wasi
endif
WASM_LDFLAGS ?= -mexec-model=reactor -Wl,--export-all -Wl,--export=malloc -Wl,--export=free -Wl,--allow-undefined -Wl,--allow-undefined-file=$(REPO_ROOT)/scripts/wasm-allowed-imports.lst
WASM_COMMON_SRC   = $(REPO_ROOT)/external/bud/src/libbud.c $(REPO_ROOT)/external/bud/src/bud_wasm_app.c
WASM_COMMON_CFLAGS = -I$(REPO_ROOT)/external/bud/include

# BSD/GNU portable: keep `all` as first target
ifeq ($(WASM_ONLY),1)
all: dirs $(WASM_TARGETS)
else
all: dirs $(TARGET) $(WASM_TARGETS)
endif
.MAIN: all

# asset version — generated by mods/common (portable, not default goal)
VERSION_GEN ?= $(REPO_ROOT)/mods/common/ux/version.gen.h
$(VERSION_GEN): $(REPO_ROOT)/htdocs/styles.css $(REPO_ROOT)/htdocs/hyle.css $(REPO_ROOT)/htdocs/bud-client.js $(REPO_ROOT)/htdocs/bud-hydrate.js $(REPO_ROOT)/htdocs/hyle-fragments.js $(REPO_ROOT)/scripts/gen-asset-version.sh
	@sh $(REPO_ROOT)/scripts/gen-asset-version.sh

$(WASM_PATH)/%.wasm: $($*-src) $(WASM_COMMON_SRC)
	@if echo 'int main(void){}' | $(WASI_CC) $(WASM_CFLAGS) -x c - -c -o /dev/null >/dev/null 2>&1; then \
		rm -f $@.d; \
		for src in $($*-src) $(WASM_COMMON_SRC); do \
			$(WASI_CC) $($*-cflags) $(WASM_COMMON_CFLAGS) $(EXTRA_CFLAGS) $(WASM_CFLAGS) -MM -MT $@ "$$src" >> $@.d || exit 1; \
		done; \
		$(WASI_CC) $($*-cflags) $(WASM_COMMON_CFLAGS) $(EXTRA_CFLAGS) $(WASM_CFLAGS) $(WASM_LDFLAGS) -o $@ $($*-src) $(WASM_COMMON_SRC); \
	else \
		echo "Skipping WASM build of $@ — install wasi-sdk or configure WASI_CC"; \
	fi

dirs:
	@for d in $(DIRS); do mkdir -p $(REPO_ROOT)/$$d 2>/dev/null || true; done

$(TARGET): $(SRC) $(MAKEFILE_DEPS)
	@rm -f $@.d; for src in $(SRC); do \
		$(CC) $(CFLAGS) -MM -MT $@ "$$src" >> $@.d || exit 1; \
	done
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(SRC) $(LDLIBS)

-include $(TARGET).d $(addsuffix .d,$(WASM_TARGETS))

wasm: $(WASM_TARGETS)

wasm-debug:
	rm -f $(WASM_TARGETS)
	$(MAKE) WASM_CFLAGS='$(WASM_CFLAGS) -DBUD_DEBUG' wasm

clean:
	if [ "$(WASM_ONLY)" != "1" ]; then rm -f $(TARGET); fi
	rm -f $(WASM_TARGETS)
	rm -f $(TARGET).d $(addsuffix .d,$(WASM_TARGETS))

distclean: clean

.PHONY: all clean distclean wasm wasm-debug
