import React from "https://esm.sh/react@18";

export function Layout({ user, title, path, children }: { user: string | null; title?: string; path?: string; children?: React.ReactNode }) {
  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <title>{title || "site"}</title>
      </head>
      <body>
        <header>
          <h1>{title || "Site"}</h1>
          {user ? <div>Welcome, {user}</div> : <div />}
        </header>
        <main>{children}</main>
        <footer>
          <small>Generated by SSR</small>
        </footer>
      </body>
    </html>
  );
}

export default Layout;
