#ifndef COMMON_DICT_H
#define COMMON_DICT_H

#include "../i18n/i18n_dict.h"

static const i18n_entry_t common_dict[] = {
	{ "Actions", "Ações" },
	{ "Add", "Adicionar" },
	{ "Add new", "Adicionar novo" },
	{ "Advanced filters", "Filtros avançados" },
	{ "All", "Todos" },
	{ "Any", "Qualquer" },
	{ "Apply", "Aplicar" },
	{ "Are you sure you want to delete", "Tem a certeza de que pretende eliminar" },
	{ "Ascending", "Ascendente" },
	{ "Author", "Autor" },
	{ "Author:", "Autor:" },
	{ "Back", "Voltar" },
	{ "Bad request", "Pedido inválido" },
	{ "Cancel", "Cancelar" },
	{ "Category", "Categoria" },
	{ "Clear", "Limpar" },
	{ "Clear all", "Limpar tudo" },
	{ "Close Menu", "Fechar menu" },
	{ "Custom", "Personalizado" },
	{ "Date", "Data" },
	{ "Delete", "Eliminar" },
	{ "Descending", "Descendente" },
	{ "Edit", "Editar" },
	{ "Filter", "Filtrar" },
	{ "Filters", "Filtros" },
	{ "Forbidden", "Acesso proibido" },
	{ "Home", "Início" },
	{ "Internal server error", "Erro interno do servidor" },
	{ "Latin", "Latim" },
	{ "Login", "Iniciar sessão" },
	{ "Logout", "Terminar sessão" },
	{ "Me", "Perfil" },
	{ "Menu", "Menu" },
	{ "Next", "Seguinte" },
	{ "Next →", "Seguinte →" },
	{ "No items found", "Nenhum item encontrado" },
	{ "Not found", "Não encontrado" },
	{ "Open", "Abrir" },
	{ "Order by", "Ordenar por" },
	{ "Page", "Página" },
	{ "Previous", "Anterior" },
	{ "Print", "Imprimir" },
	{ "Private", "Privado" },
	{ "Public", "Público" },
	{ "Register", "Registar" },
	{ "Remove", "Remover" },
	{ "Reset", "Repor" },
	{ "Save", "Guardar" },
	{ "Search", "Pesquisar" },
	{ "Search...", "Pesquisar..." },
	{ "Search…", "Pesquisar…" },
	{ "Search everything", "Pesquisar tudo" },
	{ "Search options", "Pesquisar opções" },
	{ "Status", "Estado" },
	{ "Submit", "Submeter" },
	{ "Title", "Título" },
	{ "Title:", "Título:" },
	{ "Type", "Tipo" },
	{ "Unauthorized", "Não autorizado" },
	{ "Username", "Nome de utilizador" },
	{ "Username:", "Nome de utilizador:" },
	{ "View PDF", "Ver PDF" },
	{ "Watch on YouTube", "Ver no YouTube" },
	{ "Wrap lines", "Quebrar linhas" },
	{ "Zoom", "Zoom" },
	{ "← Prev", "← Anterior" },
	{ " / page", " / página" },
	{ "/ page", "/ página" },
	{ "de", "de" },
	{ "delete", "eliminar" },
	{ "edit", "editar" },
	{ "login", "iniciar sessão" },
	{ "logout", "terminar sessão" },
	{ "me", "perfil" },
	{ "of", "de" },
	{ "options", "opções" },
	{ "register", "registar" },
	{ "rows", "linhas" }
};

#define COMMON_DICT_COUNT (sizeof(common_dict) / sizeof(common_dict[0]))

#endif /* COMMON_DICT_H */
