EXTRA_CFLAGS += -I../../external/bud/include
EXTRA_LDLIBS += -L../../external/bud/lib -lbud

$(TARGET): ux/site_ui.c ux/site_chrome.c ux/site_chrome.h common_encoding.c common_response.c common_storage.c common_strlist.c

include ../../build.mk
